name: EVO Custom Design
url: https://sfjorge.github.io/jekyllthemes/
description: EVO Custom Design Specialists in Design, Development and Remodeling of Real Estate. evocustomdesign@gmail.com Miami, Fl. 7863621579 / 7864788932

permalink: /themes/:title/

gems: [jekyll-paginate]

highlighter: pygments
paginate: 20

markdown: rdiscount
rdiscount:
    extensions: ['smart']

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile', 'vendor']
